### ISSUE TITLE
Sample Game Missing dxerr.lib

### ISSUE THREAD

**Issue by Manuzor** [dimitrikourk/small3d#27]
When trying to build `dimitrikourk_small3d_samplegame_main`, I get the following linker error:
```
LINK : fatal error LNK1104: cannot open file 'dxerr.lib'
```

I'm running Windows 8 64 bit, using `bii configure -G "Visual Studio 12"` to create the Visual Studio project/solution file. I am using [small3d version 1(1.0.1) from biicode](https://www.biicode.com/dimitrikourk/small3d).

Note: I do have the DXSDK installed (June 2010 or whatever) and the environment variable `DXSDK_DIR` is set. I have a bunch of other projects that depend on this, so I am sure that it is installed correctly.

**Comment by dimitrikourk** [comment]
Hello,

I have just performed a test and I am afraid I cannot reproduce the problem :( I think that the directx is only used for sound, via the PortAudio dependency. Apparently that library you mention is needed and the build cannot find it on your system. Have you tried re-installing directx?

Thanks for letting me know in any case.

**Comment by Manuzor** [comment]
I didn't reinstall Directx yet, but I tried removing the dxerr.lib dependency manually (from the CMake generated Visual Studio solution) and expected linker errors... but got none. The sample game ran fine without it. Apparently it finds the dinput8.lib as well as the dxguid.lib, but not dxerr.lib, even though they all live in the same folder... :confused:

I'm not exactly sure where the DirectX dependencies are set. Could you maybe check where they expect DirectX to live? Because I have it installed in a non-standard location.

Thanks!

**Comment by dimitrikourk** [comment]
Once again, apologies for the very long delay.

If the game runs and there are no link errors, it could be that dxerr.lib is really not needed.

Interestingly enough, I cannot find this file on my system. Portaudio tries to find DXSDK here:
https://github.com/dimitrikourk/biicodePortAudio/blob/master/CMakeLists.txt

I am building using bii configure -G "Visual Studio 12" too. I never explicitly installed DirectX SDK. I am using Windows 8 too by the way, and DirectX is integrated there as part of the Windows SDK as far as I know (https://msdn.microsoft.com/en-us/library/windows/desktop/ee663275%28v=vs.85%29.aspx)

If you have explicitly installed the 2010 version of DirectX, perhaps simply uninstalling it would help get rid of the problem?
